# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21.0"

      - name: Set filename based on OS
        run: |
          if [ ${{ matrix.os }} == "ubuntu-latest" ]; then
            echo "FIB_FILENAME=fib.so" >> $GITHUB_ENV
          elif [ ${{ matrix.os }} == "macos-latest" ]; then
            echo "FIB_FILENAME=fib.dylib" >> $GITHUB_ENV
          elif [ ${{ matrix.os }} == "windows-latest" ]; then
            echo "FIB_FILENAME=fib.dll" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Compile Go code
        run: go build -buildmode=c-shared -o $FIB_FILENAME
        shell: bash

      - name: Run/test
        run: python main.py
        shell: bash
